# Generated by Django 5.2.8 on 2026-04-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_timestamp_to_sensorreading'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensorreading',
            unique_together=set(),
        ),
    ]
